development:
  adapter: postgresql
  encoding: utf8
  database: simpleblog_development
  pool: 5
  username: bogdan
  password: '11111111'

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: simpleblog_test
  pool: 5
  username: bogdan
  password: '11111111'

production:
  adapter: postgresql
  encoding: utf8
  database: simpleblog_production
  pool: 5
  username: bogdan
  password: '11111111'
